### ISSUE TITLE
在使用插件SauceNao搜图时，有概率抛出空指针异常

### ISSUE THREAD

**Issue by MoeMegu** [Nekoer/mirai-plugins-pixiv#1]
JVM版本:temurin-11 windows x86
Mirai版本:2.8.0
出现问题的代码:
at com.hcyacg.search.Saucenao.picToSearch(Saucenao.kt:92)
at com.hcyacg.search.Saucenao.picToSearch(Saucenao.kt:95)
使用ptst-[图片]指令，调用SauceNAO搜图时，程序概率性抛出空指针异常，可复现
![QQ截图20211115151418](https://user-images.githubusercontent.com/25688691/141740012-59b78c2f-9e31-402e-ad89-4b9202159cca.png)
![QQ截图20211115152111](https://user-images.githubusercontent.com/25688691/141740033-4163eab2-6538-4203-a528-ccf04d9f5dcb.png)

**Comment by Nekoer** [comment]
请提供源图，打包上传

**Comment by MoeMegu** [comment]
[源图片.zip](https://github.com/Nekoer/mirai-plugins-pixiv/files/7537077/default.zip)
提供源图与堆栈跟踪

**Comment by Nekoer** [comment]
> [源图片.zip](https://github.com/Nekoer/mirai-plugins-pixiv/files/7537077/default.zip) 提供源图与堆栈跟踪
![image](https://user-images.githubusercontent.com/32485369/141763648-657727b2-2b5c-4447-954b-0fa0fdbb0f42.png)
大概是网络不稳定导致的，检查下你代理的网络质量及当前token的使用次数是否达到上限
