### ISSUE TITLE
【Bug反馈】lolicon reload失效

### ISSUE THREAD

**Issue by rong-xiaoli** [Nekoer/mirai-plugins-pixiv#12]
输入lolicon reload后，显示参数不匹配
而输入lolicon help后，会有：
/lolicon reload    # 重载插件配置和数据
这一命令
请问是不是尚未完成的命令？

**Comment by Nekoer** [comment]
你找错插件了吧
我这没有这个命令

**Comment by rong-xiaoli** [comment]
好的，感谢，close了
