### ISSUE TITLE
当作品数量小于等于10，user功能显示作品为空

### ISSUE THREAD

**Issue by buggzd** [Nekoer/mirai-plugins-pixiv#4]
当使用user功能时，对应的user的作品数量小于等于10时，只会显示作品数量，作品列表显示为空。
![qq](https://user-images.githubusercontent.com/57561662/158565040-72cdbc0b-6615-41f0-a2e4-39fac244125c.jpg)

**Comment by Nekoer** [comment]
该问题已在1.6.4修改

**Comment by Nekoer** [comment]
fix
