### ISSUE TITLE
会员充值成功后仍判断需要会员

### ISSUE THREAD

**Issue by Tamamoimoto** [Nekoer/mirai-plugins-pixiv#47]
### 问题描述

BOT发出二维码，支付宝扫码充值后，机器人仍然提示需要充值会员。

### 复现

1.发出指令-充值月费会员
2.BOT发出二维码，使用支付宝扫码并支付成功
3.发出指令-rank-daily_r18-1
4.BOT还是提示需要充值会员

### pixiv 版本

1.7.4

**Comment by Nekoer** [comment]
fix
