### ISSUE TITLE
能不能加一个过滤r18作品功能啊）

### ISSUE THREAD

**Issue by NinetyXD** [Nekoer/mirai-plugins-pixiv#50]
求加一个过滤r18作品的功能

**Comment by Nekoer** [comment]
功能已有，自己找找

**Comment by modeilan** [comment]
> 功能已有，自己找找

大佬只看个个涩图开关，关了非r18都看不了了

**Comment by Nekoer** [comment]
> 大佬只看个个涩图开关，关了非r18都看不了了
看不了说明该图片里有r18标签或者san值达到涩图分值
