### ISSUE TITLE
使用mirai管理的./mcl安装方式无法正确使用fix版本

### ISSUE THREAD

**Issue by qyh214** [Nekoer/mirai-plugins-pixiv#57]
### 问题描述
使用`./mcl --update-package com.hcyacg:pixiv --channel stable --type plugin`更新到fix版本后，无法启动

### 复现

使用`./mcl --update-package com.hcyacg:pixiv --channel stable --type plugin`启动，此时会获取最新fix版本，然后关闭，再次启动

### pixiv 版本

1.7.4-fix

**Comment by Nekoer** [comment]
你把根目录config.json里的pixiv删了就行

**Comment by qyh214** [comment]
> 你把根目录config.json里的pixiv删了就行

嗯嗯，不过这样就不能统一更新了，应该属于mirai的问题……
