### ISSUE TITLE
建议增加对群消息图片引用触发对应指令

### ISSUE THREAD

**Issue by jsyishan** [Nekoer/mirai-plugins-pixiv#58]
场景是 群里已经有人发过一张图，然后比如想“检测”，就得自己下载到本地，再发送“检测+图片“（移动端），只有pc端可以简单拖拽复制。

**Comment by Nekoer** [comment]
更改为延迟发送图片的方式
[a3c6da6](https://github.com/Nekoer/mirai-plugins-pixiv/commit/a3c6da6bc48857950875ecba47ef4c9ec6d45ed0)
