### ISSUE TITLE
如果色图功能能直接加标签就好了

### ISSUE THREAD

**Issue by jinxx52** [Nekoer/mirai-plugins-pixiv#6]
比如 
来点色图 甘雨
就会输出甘雨的
来点色图 甘雨 r18
就是r18版本的图
现在这个版本似乎只能随机色图和较为繁琐的查id然后再指定图片id色图

**Comment by Nekoer** [comment]
这种只能靠yande的tag来搜了，下一个版本会提供setu指定tag
