### ISSUE TITLE
Config文件被重置

### ISSUE THREAD

**Issue by ccxxvv77** [Nekoer/mirai-plugins-pixiv#69]
### 问题描述

平台

> Mirai Console v2.14.0
> WinServer 2022
> OpenJDK 18

插件列表

> fix-protocol-version v1.2.0
> mirai-login-solver-sakura v0.0.9
> mirai-new-bing v0.3.1
> pixiv插画 v1.7.5
> bilibili-helper v1.6.7
> MCL Addon v2.1.1

每次开启Mirai的时候 ```config\com.hcyacg.pixiv``` 下的

> Command.yml
> Config.yml
> Settings.yml

都会被重置

### 复现

使用Github Release的1.7.5文件手动拖到plugins安装
正常 ./mcl.bat 启动
然后三个配置文件就会被重置
改完重启mcl仍然会被重置

### pixiv 版本

1.7.5

**Comment by Nekoer** [comment]
请关闭机器人后修改配置
