### ISSUE TITLE
装上了之后，mcl.cmd加载到灰色的字段后退出

### ISSUE THREAD

**Issue by himetuki** [Nekoer/mirai-plugins-pixiv#70]
### 问题描述

闪退。第一次正常启动，但是发现不能使用指令，于是我/exit，更改config里的setting文件，与你的相同，当然其中QQ号部分改成我自己的了，在这次之后，就闪退了！就算我把config中的pixiv相关的文件夹删了，还是会闪退

### 复现

用终端下载插件，然后打开mcl.cmd让其自然运行，然后闪退

### pixiv 版本

1.6.8

### 系统日志

```text
/
```

### 网络日志

```text
。
```

### 补充信息

日志是什么？我一直想问，如果是命令行里头的，那闪退来不及保存。
还有请问这个issue里头pixiv版本是什么

**Comment by Nekoer** [comment]
首先：配置文件已经分为3个，你不能完全copy我的配置文件
其次：我并没有看到任何日志，无法给你解决
