### ISSUE TITLE
建议增加主人QQ私聊添加涩图权限的功能

### ISSUE THREAD

**Issue by smilecat2788** [Nekoer/mirai-plugins-pixiv#73]
目前增加有涩图权限的群需要手动修改配置文件或者主人加入群聊修改，当群聊过多这无疑是个麻烦，希望可以添加一条命令，可以在私聊环境下指定某个群聊开启或关闭涩图权限

**Comment by Nekoer** [comment]
https://github.com/Nekoer/mirai-plugins-pixiv/commit/4a5d290eb88228e1e2a3d5621671632105744859
