### ISSUE TITLE
i.acgmx.com站点无法访问

### ISSUE THREAD

**Issue by MoeShimaKaze** [Nekoer/mirai-plugins-pixiv#80]
### 问题描述

i.acgmx.com挂了无法访问，看看啥时候能恢复

### 复现

浏览器访问i.acgmx.com，提示超时

### pixiv 版本

1.7.8

**Comment by Nekoer** [comment]
主机商区域网络调整，已修复

**Comment by MoeShimaKaze** [comment]
主站acgmx.com打不开了，有什么头绪吗？
现在psid功能直接用不了了
而且好像mirai上，没法正常使用识图

**Comment by Nekoer** [comment]
稍等，ip被服务商变了:(

**Comment by Nekoer** [comment]
已经更换，恢复访问了

**Comment by Nekoer** [comment]
> 识图
你用的是什么版本的插件

**Comment by MoeShimaKaze** [comment]
> > 识图
> > 你用的是什么版本的插件

之前使用1.7.8的版本，也是不可以的，后来换了actions构建里的版本，也是一样，现在用的action构建里的

**Comment by MoeShimaKaze** [comment]
> 已经更换，恢复访问了

网页可以打开，但是图片加载不出来？是我的问题吗

**Comment by Nekoer** [comment]
> > 已经更换，恢复访问了
> 
> 网页可以打开，但是图片加载不出来？是我的问题吗

程序用到邮箱端口，运营商没开放，导致程序无法正常运行。需要明天再看看，刚提了工单

**Comment by Nekoer** [comment]
> > > 识图
> > > 你用的是什么版本的插件
> 
> 之前使用1.7.8的版本，也是不可以的，后来换了actions构建里的版本，也是一样，现在用的action构建里的

可能是最新的一次提交action没成功，那一版修复了搜图

**Comment by MoeShimaKaze** [comment]
> > > > 识图
> > > > 你用的是什么版本的插件
> > 
> > 
> > 之前使用1.7.8的版本，也是不可以的，后来换了actions构建里的版本，也是一样，现在用的action构建里的
> 
> 可能是最新的一次提交action没成功，那一版修复了搜图

方便修复一下吗，这个功能还蛮重要的

**Comment by MoeShimaKaze** [comment]
> > > 已经更换，恢复访问了
> > 
> > 
> > 网页可以打开，但是图片加载不出来？是我的问题吗
> 
> 程序用到邮箱端口，运营商没开放，导致程序无法正常运行。api已经恢复了

这样的话，网页没法打开然后相应的支付服务也挂了，目前想充值月度会员好像也不可用（

**Comment by Nekoer** [comment]
> > > > 已经更换，恢复访问了
> > > 
> > > 
> > > 网页可以打开，但是图片加载不出来？是我的问题吗
> > 
> > 
> > 程序用到邮箱端口，运营商没开放，导致程序无法正常运行。api已经恢复了
> 
> 这样的话，网页没法打开然后相应的支付服务也挂了，目前想充值月度会员好像也不可用（

均已恢复
